### ISSUE TITLE
Absolute positioning edge-cases

### ISSUE THREAD

**Issue by brunnerh** [GoogleChromeLabs/css-triggers#48]
I just found out that at the very least Chrome does not always cause paint if an element is positioned absolutely and has its own layer.

If the `go` function on the subsequent `top` change  test page only moves the outer element and not all the elements there is no paint. I changed it like this:

```js
go = () => document.querySelector("#targetElement").style.top = "30%";
```

Not sure what the issue is when the class is applied, as all the children are also positioned absolutely with `will-change`. Intuitively it makes sense to me that absolutely positioned elements do not invalidate any pixels if they have their own layer.

**Comment by surma** [comment]
Hm, I whipped up a quick [JSBin](https://jsbin.com/batugut/1/edit?output), there’s definitely layout, paint & compositing happening:

<img width="1917" alt="screen shot 2017-10-09 at 11 37 52 am" src="https://user-images.githubusercontent.com/234957/31334527-8c59c262-ace6-11e7-9131-bd27a1dc00f8.png">

Do you have a test case you can give me where layout is not triggered? Genuinely curious.

I think you are right that there _might_ be an optimization to not trigger layout & paint on a promoted, absolutely positioned element, but I am not sure it’s trivial.

**Comment by brunnerh** [comment]
I never said that layout would not be triggered, but paint is not necessarily triggered. I do not know of any case where layout can be circumvented.

![image](https://user-images.githubusercontent.com/834235/31349070-f5ec6af0-ad21-11e7-8f80-b39b6e4bbd14.png)

The code for that page:

```html
<html>
<head>
	<style>
		.abs {
			position: absolute;
			top: 10px;
			will-change: top;
			width: 100px;
			height: 100px;
			background: lightgreen;
		}

		.abs.move {
			top: 30px;
		}
	</style>
</head>

<body>
	<div class="abs"></div>

	<script>
		var move = () => document.querySelector(".abs").classList.toggle("move");
		setInterval(move, 500);
	</script>
</body>
</html>
```

**Comment by brunnerh** [comment]
I tested this on 61.0.3163.100 actually. Interacting with the dev tools can cause paints by the way; not sure if they show up at the location triggered by the script and are prone to cause confusion though.
